[package]
name = "of-client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

anyhow = "1.0.66"

log = "0.4.17"

futures = "0.3.21"
futures-util = "0.3.21"

strip_markdown = "0.2.0"
serde = { version = "1.0.140", features = ["derive"] }

rust-crypto = "0.2.36"
rand = "0.8.5"
rand_distr = "0.4.3"

cached = "0.44.0"
chrono = "0.4.19"
filetime = "0.2.17"
reqwest = { version = "0.11.11", features = ["cookies", "gzip", "json", "stream"] }
