[package]
name = "of-notifier"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
chrono = "0.4.19"
tempfile = "3.3.0"
serde_json = "1.0.82"
rust-crypto = "0.2.36"
futures-util = "0.3.21"
winrt-notification = "0.5.1"
tokio = { version = "1.20.0", features = ["full"] }
serde = { version = "1.0.140", features = ["derive"] }
reqwest = { version = "0.11.11", features = ["cookies", "gzip"] }
tokio-tungstenite = { version = "0.17.2", features = ["native-tls"] }
