[package]
name = "of-notifier"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.17"
rand = "0.8.5"
winit = "0.25"
chrono = "0.4.19"
cached = "0.38.0"
futures = "0.3.21"
tempfile = "3.3.0"
filetime = "0.2.17"
simplelog = "0.12.0"
tokio-util = "0.7.3"
serde_json = "1.0.82"
winrt-toast = "0.1.1"
async-trait = "0.1.57"
rust-crypto = "0.2.36"
futures-util = "0.3.21"
strip_markdown = "0.2.0"
tokio = { version = "1.20.0", features = ["full"] }
serde = { version = "1.0.140", features = ["derive"] }
trayicon = { version = "0.1.3", features = ["winit"] }
reqwest = { version = "0.11.11", features = ["cookies", "gzip"] }
tokio-tungstenite = { version = "0.17.2", features = ["native-tls"] }
